
services:

  workstation:
    build: workstation/
    image: workstation
    container_name: workstation
    hostname: workstation
    runtime: sysbox-runc
    ports:
      - "2200:22"
    networks:
      - ansible-lab

  node1:
    build: server/
    image: server
    container_name: node1
    hostname: node1
    runtime: sysbox-runc
    ports:
      - "2201:22"
    networks:
      - ansible-lab

  node2:
    image: server
    container_name: node2
    hostname: node2
    runtime: sysbox-runc
    ports:
      - "2202:22"
    networks:
      - ansible-lab
    depends_on:    # incase server image isn't built yet
      - node1

  node3:
    image: server
    container_name: node3
    hostname: node3
    runtime: sysbox-runc
    ports:
      - "2203:22"
    networks:
      - ansible-lab
    depends_on:    # incase server image isn't built yet
      - node1

  node4:
    image: server
    container_name: node4
    hostname: node4
    runtime: sysbox-runc
    ports:
      - "2204:22"
    networks:
      - ansible-lab
    depends_on:    # incase server image isn't built yet
      - node1

  node5:
    image: server
    container_name: node5
    hostname: node5
    runtime: sysbox-runc
    ports:
      - "2205:22"
    networks:
      - ansible-lab
    depends_on:    # incase server image isn't built yet
      - node1


networks:
  ansible-lab:
    name: ansible-lab
